apiVersion: v1
kind: Service
metadata:
  name: hellospring-service
  labels:
    app: hellospring-java-app
  namespace: java-apps
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: hellospring-java-app
  type: ClusterIP